language: node_js

node_js:
  - "0.12"
  - "4"
  - "6"

before_install:
  - curl -s -L https://www.arangodb.com/repositories/travisCI/setup_arangodb_2.8.11.sh -o setup_arangodb.sh
  - chmod +x setup_arangodb.sh
  - ./setup_arangodb.sh

after_success:
  - grunt coveralls

after_script:
  - ./test/travis/teardown_arangodb.sh